version: "3.7"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8080:8000
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

  db:
    image: postgres
    environment:
      POSTGRES_USER: tupa
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: celeryproject
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
